### ISSUE TITLE
React Native 0.14 Support

### ISSUE THREAD

**Issue by sonnylazuardi** [teamrota/react-native-gmaps#4]
When I'm using react native 0.14 i got the following error:

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
Unknown source file : 	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
Unknown source file : 	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

```

**Comment by sonnylazuardi** [comment]
solved using : http://developer.android.com/tools/building/multidex.html
