### ISSUE TITLE
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION

### ISSUE THREAD

**Issue by ACCTFORGH** [teamrota/react-native-gmaps#7]
I was following the installation steps but encountered the errors below when running react-native run-android.

I am using RN-0.14 for Android platform, development on OS X with Genymotion. After some search, it seems to be there are too many methods in my app but I believe my project itself does not reach the 65k methods limit. Would really appreciate your help! Thank!!

Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
Unknown source file : 	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
Unknown source file : 	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by ACCTFORGH** [comment]
Alright, I figured how it works, reference to https://github.com/teamrota/react-native-gmaps/issues/6, we should change the google play dependency at the build.grade of react-native-maps to be google map specific only

compile "com.google.android.gms:play-services-maps:8.1.0"

the current installation installs the whole play services packages, that's why there is the 65k methods limit reached.

**Comment by christocracy** [comment]
I've fixed this dependency issue in my PR #9

**Comment by christocracy** [comment]
I raised this issue in #6
